# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ca864da839e060f76e3aad0bef18c0e90589eb6926045c5c5d7d53f3a135bfa5a3359c5fb5c63c11d8cabbc601ef855e356468f5e3aa65e243cdab9d9662f93

test:
  secret_key_base: c934ba7827149979227b2582b236f3d632ac76b9b3cd0062ed9ff380116807b0a79200eeb093f9435475f55b3caf47785760dc9bd1f07e2b98fc4db5436b8818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
